name: Lint VC Vocabulary
on:
  pull_request:
    paths:
    - 'vocab/security/vocabulary.yml'
    - 'vocab/security/template.html'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: actions/checkout/@v5
      - name: Setup Node 24
        uses: actions/setup-node@v5
        with:
          node-version: 24
      - name: Lint Security Vocabulary
        run: |
          npm install yml2vocab
          npm update yml2vocab
          ./node_modules/.bin/yml2vocab -v vocab/security/vocabulary.yml -t vocab/security/template.html
